### ISSUE TITLE
Feature Request: Schedule Date

### ISSUE THREAD

**Issue by AdrieanKhisbe** [zmandel/Plus-for-Trello#9]
Here is a suggested feature that could be added to awesome trello+ :)

The ability to be setting a scehduled date for the task to be done.
(then ability to fade out card according this date could be added on top)

This could be done with a magic comment, but I guess that you might have other ideas.

Ps: I could help set up the feature if I'm hooked up. (Or contribute setting up test structure and CI)

**Comment by zmandel** [comment]
how would this be different from using due dates?

**Comment by AdrieanKhisbe** [comment]
In term of implementation not much I'll say.
It's in term of usage, feature. To capture some things like this:

> I have  to do this for thursday, but I can only start on tuesday

**Comment by zmandel** [comment]
sorry somehow github didn't notice me of your reply.
So its a "start date", and the due date is the "end date", right?
I plan to eventually support something similar for gantt purposes. However threre are some decisions to be made. in particular, how to maintain both dates in sync as the user changes one or the other, or modifies the Estimation. Would the estimation be used to calculate a new due date, based on this start date? Would start dates be per-user? if so, they cant go together with due dates, as those are per card, not per user+card pair. All these need to be resolved before opening that "can". My plan is to also have the ability to tie start dates to end dates of other cards, thus allowing dependencies. But so far because Im planning to integrate this with card "due dates", I havent considered doing it per user+card, and only per-card, for gantt purposes (since it will have card dependencies, you could always split a card into many, with one user per card to avoid the issue of due dates being only per-card). Also please write to support@plusfortrello.com if in the future I miss a reply.

**Comment by AmauryVanEspen** [comment]
Hello
Is there some update about the topic of start date - time
Maybe a link with the Agenda feature (estimate as the Lenght in Agenda)
Thank you
Amaury

**Comment by zmandel** [comment]
sorry, not planned for Plus

**Comment by AdrieanKhisbe** [comment]
> Also please write to support@plusfortrello.com if in the future I miss a reply.

@zmandel seems like I missed your reply too :grin:
